server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: 'sa'
        #platform: mysql
        #url: jdbc:mysql://localhost/delivery-order?verifyServerCertificate=false&useSSL=false&requireSSL=false
        url: jdbc:mysql://localhost/pendotiba-garage
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2008Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
      id: garages
